# Generated by Django 5.2.6 on 2025-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SymptomEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom", models.CharField(max_length=200, unique=True)),
                (
                    "possible_causes",
                    models.TextField(help_text="Comma separated causes"),
                ),
                (
                    "treatments",
                    models.TextField(help_text="Use | to separate multiple treatments"),
                ),
                ("language", models.CharField(default="en", max_length=20)),
            ],
        ),
    ]
